defaults:
  - _self_
  - ../joint/left/airexo.yaml@airexo_left_joint_cfgs  # left joint configuration for AirExo-2
  - ../joint/right/airexo.yaml@airexo_right_joint_cfgs  # right joint configuration for AirExo-2
  - ../joint/left/robot.yaml@robot_left_joint_cfgs  # left joint configuration for robot
  - ../joint/right/robot.yaml@robot_right_joint_cfgs  # right joint configuration for robot
  - ../joint/left/calib.yaml@left_calib_cfgs  # left joint calibration configuration
  - ../joint/right/calib.yaml@right_calib_cfgs  # right joint calibration configuration
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

type: wild  # choices: teleop, wild
path: "/home/ubuntu/data/"  # path to save data
cameras:  # list of camera serials
  - "104122061602"
camera_freq: 20  # camera frequency

controller:  # controller configuration
  _target_: airexo.collection.controller.DualArmController  # we do not need a controller for in-the-wild data collection, thus we use a dummy controller

  left_arm:  # left arm configuration
    _target_: airexo.collection.controller.SingleArmDummyController
    airexo:  # AirExo configuration
      _target_: airexo.device.airexo.AirExo
      port: /dev/ttyUSB2
      joint_cfgs: ${airexo_left_joint_cfgs}
      baudrate: 115200
      sleep_gap: 0.0016
      logger_name: AirExo-left
    logger_name: DummyCtrl-left  # logger name

  right_arm:  # right arm configuration
    _target_: airexo.collection.controller.SingleArmDummyController
    airexo:  # AirExo configuration
      _target_: airexo.device.airexo.AirExo
      port: /dev/ttyUSB3
      joint_cfgs: ${airexo_right_joint_cfgs}
      baudrate: 115200
      sleep_gap: 0.0016
      logger_name: AirExo-right
    logger_name: DummyCtrl-right  # logger name

lowdim_collectors:  # list of low-dimensional collectors
  - _target_: airexo.collection.collector.LowdimCollector
    name: "airexo_left"  # key of the collector
    controller_key: ["left_arm", "airexo"]  # key link trajectory to the object, whose state will be collected. This object should implement `get_state()`
    freq: 60  # frequency of data collection
    buffer_size: 1000  # buffer size
  - _target_: airexo.collection.collector.LowdimCollector
    name: "airexo_right"
    controller_key: ["right_arm", "airexo"]
    freq: 60
    buffer_size: 1000
