defaults:
  - _self_
  - ../joint/left/robot.yaml@robot_left_joint_cfgs
  - ../joint/left/airexo.yaml@airexo_left_joint_cfgs
  - ../joint/left/calib.yaml@left_calib_cfgs
  - ../joint/right/robot.yaml@robot_right_joint_cfgs
  - ../joint/right/airexo.yaml@airexo_right_joint_cfgs
  - ../joint/right/calib.yaml@right_calib_cfgs
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

_target_: airexo.helpers.visualizer.AirExoRGBVisualizer

config_camera_path: airexo/configs/cameras
camera_serial: "104122061602"

calib_info:
  _target_: airexo.calibration.calib_info.CalibrationInfo
  calib_path: /home/ubuntu/data/calib_airexo
  calib_timestamp: 1737226610748

urdf_file: airexo/urdf_models/airexo/airexo.urdf

alpha: 0.6
near_plane: 0.01
far_plane: 100.0

left_airexo:
  _target_: airexo.device.airexo.AirExo
  port: /dev/ttyUSB2
  joint_cfgs: ${airexo_left_joint_cfgs}
  baudrate: 115200
  sleep_gap: 0.0016
  logger_name: AirExo-left
  
right_airexo: 
  _target_: airexo.device.airexo.AirExo
  port: /dev/ttyUSB3
  joint_cfgs: ${airexo_right_joint_cfgs}
  baudrate: 115200
  sleep_gap: 0.0016
  logger_name: AirExo-right

