defaults:
  - _self_
  - ../joint/left/robot.yaml@robot_left_joint_cfgs
  - ../joint/left/airexo.yaml@airexo_left_joint_cfgs
  - ../joint/left/calib.yaml@left_calib_cfgs
  - ../joint/right/robot.yaml@robot_right_joint_cfgs
  - ../joint/right/airexo.yaml@airexo_right_joint_cfgs
  - ../joint/right/calib.yaml@right_calib_cfgs
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

path: null

camera_serial: "104122061602"

calib_info:
  _target_: airexo.calibration.calib_info.CalibrationInfo
  calib_path: /home/jingjing/workspace/sp1/AirExo-2/airexo/assets/calib_airexo/
  calib_timestamp: 1737226610748

urdf_file: airexo/urdf_models/airexo/airexo.urdf

gripper_width_threshold: 0.002