defaults:
  - _self_
  - ../joint/left/airexo.yaml@airexo_left_joint_cfgs
  - ../joint/left/calib.yaml@left_calib_cfgs
  - ../joint/right/airexo.yaml@airexo_right_joint_cfgs
  - ../joint/right/calib.yaml@right_calib_cfgs
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

type: annotator

annotator:
  _target_: airexo.calibration.annotator.AnnotateAirExo2DCalibratorFromCamera

  calib_info: 
    _target_: airexo.calibration.calib_info.CalibrationInfo
    calib_path: /home/ubuntu/data/calib_airexo
    calib_timestamp: 1737226610748

  config_camera_path: airexo/configs/cameras
  camera_serial: "104122061602"

  left_airexo:
    _target_: airexo.device.airexo.AirExo
    port: /dev/ttyUSB2
    joint_cfgs: ${airexo_left_joint_cfgs}
    baudrate: 115200
    sleep_gap: 0.0016
    logger_name: AirExo-left
    
  right_airexo: 
    _target_: airexo.device.airexo.AirExo
    port: /dev/ttyUSB3
    joint_cfgs: ${airexo_right_joint_cfgs}
    baudrate: 115200
    sleep_gap: 0.0016
    logger_name: AirExo-right

  left_calib_cfgs: ${left_calib_cfgs}
  right_calib_cfgs: ${right_calib_cfgs}

  urdf_file: airexo/urdf_models/airexo/airexo.urdf
  
  near_plane: 0.01
  far_plane: 100.0
  initial_line_speed: 0.003
  initial_angle_speed: 0.0087266463
  line_step: 0.0005
  angle_step: 0.0010908308

annotator_params:
  save_path: null
