defaults:
  - _self_
  - ../joint/left/airexo.yaml@airexo_left_joint_cfgs
  - ../joint/left/calib.yaml@left_calib_cfgs
  - ../joint/right/airexo.yaml@airexo_right_joint_cfgs
  - ../joint/right/calib.yaml@right_calib_cfgs
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

type: annotator

annotator:
  _target_: airexo.calibration.annotator.AnnotateAirExo2DCalibratorFromData

  calib_info: 
    _target_: airexo.calibration.calib_info.CalibrationInfo
    calib_path: /home/ubuntu/data/calib_airexo
    calib_timestamp: 1737226610748

  camera_serial: "104122061602"

  airexo_left_joint_cfgs: ${airexo_left_joint_cfgs}
  airexo_right_joint_cfgs: ${airexo_right_joint_cfgs}
  left_calib_cfgs: ${left_calib_cfgs}
  right_calib_cfgs: ${right_calib_cfgs}

  urdf_file: airexo/urdf_models/airexo/airexo.urdf
  
  near_plane: 0.01
  far_plane: 100.0
  initial_line_speed: 0.001
  initial_angle_speed: 0.0087266463
  line_step: 0.00002
  angle_step: 0.0001908308
  timestamp_step: 1

annotator_params:
  data_path: /home/ubuntu/data/task_0013_wild/scene_0005
  save_path: /home/ubuntu/data/test_calib/
  
