num_joints: 8
num_robot_joints: 7
joint1:
  id: 1
  min: 200.126
  max: 167.871
  direction: 1
  rad: False
joint2:
  id: 2
  min: 5.449
  max: 347.478
  direction: 1
  rad: False
joint3:
  id: 3
  min: 210.673
  max: 198.017
  direction: 1
  rad: False
joint4:
  id: 4
  min: 227.285
  max: 218.583
  direction: 1
  rad: False
joint5:
  id: 5
  min: 157.236
  max: 146.689
  direction: 1
  rad: False
joint6:
  id: 6
  min: 174.814
  max: 160.136
  direction: 1
  rad: False
joint7:
  id: 7
  min: 306.474
  max: 294.169
  direction: 1
  rad: False
joint8:
  id: 8
  min: 70
  max: 5
  direction: 1
  rad: False