num_joints: 8
num_robot_joints: 7
joint1:
  fixed: False
  fixed_value: 0
  init_value: 73.14
  min: 159.5
  max: 200.5
  direction: -1
  rad: True
  zero_centered: True
joint2:
  fixed: False
  fixed_value: 0
  init_value: 233.36
  min: 129.5
  max: 230.5
  direction: -1
  rad: True
  zero_centered: True
joint3:
  fixed: False
  fixed_value: 0
  init_value: 62.90
  min: 169.5
  max: 190.5
  direction: -1
  rad: True
  zero_centered: True
joint4:
  fixed: False
  fixed_value: 0
  init_value: 256.36
  min: 50.5
  max: 253.5
  direction: -1
  rad: True
  zero_centered: True
joint5:
  fixed: False
  fixed_value: 0
  init_value: 0
  min: 169.5
  max: 190.5
  direction: -1
  rad: True
  zero_centered: True
joint6:
  fixed: False
  fixed_value: 0
  init_value: 340.75
  min: 259.5
  max: 280.5
  direction: -1
  rad: True
  zero_centered: True
joint7:
  fixed: False
  fixed_value: 0
  init_value: 0
  min: 169.5
  max: 190.5
  direction: -1
  rad: True
  zero_centered: True
joint8:
  fixed: False
  fixed_value: 0
  init_value: 0
  min: 0
  max: 0.17