defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# 外部路径配置
urdf_path: "airexo/urdf_models/robot/true_robot.urdf"
csv_file_path: "/home/ryan/Documents/GitHub/AirExo-2-test/train_video/hand_landmarks_3d_offline.csv"
render_output_dir: "/home/ryan/Documents/GitHub/AirExo-2-test/rendered/images"

# 新增：直接定义相机内外参，取代 calib_info
camera_params:
  # 相机在世界坐标系下的位姿 (外参)
  cam_to_base:
    translation: [0.3, -0.7, 1.41]
    rpy: [1.5708, 0.0, -1.5708] # [90度, 0度, -90度]
  # 相机内参
  intrinsic:
    fx: 915.025
    fy: 914.881
    cx: 640.0
    cy: 360.0

robot_renderer:
  _target_: airexo.helpers.renderer.RobotRenderer
  width: 1280
  height: 720
  near_plane: 0.01
  far_plane: 100.0
  urdf_file: airexo/urdf_models/robot/true_robot.urdf
  left_joint_cfgs:
    _target_: airexo.helpers.constants.RobotJoints
    joint_names: ["l_joint1", "l_joint2", "l_joint3", "l_joint4", "l_joint5", "l_joint6", "l_joint7"]
    num_joints: 7
  right_joint_cfgs:
    _target_: airexo.helpers.constants.RobotJoints
    joint_names: ["r_joint1", "r_joint2", "r_joint3", "r_joint4", "r_joint5", "r_joint6", "r_joint7"]
    num_joints: 7

# IK 求解器参数 (保持不变)
ik:
  per_joint_max_delta: 0.15
  total_max_delta: 0.4
  noise_level: 0.2
  ik_attempts: 20
  lambda_weight: 0.1
  active_joint_names: ['r_joint1', 'r_joint2', 'r_joint3', 'r_joint4', 'r_joint5', 'r_joint6', 'r_joint7']
  q_start_values: [1.2, 1.21, 0.82, 0.56, 0.0, 0.0, 0.0]